update run script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,5 +1,27 @@
 #!/usr/bin/env bash
 
+
+# make sure these files exist
+if [ ! -f "requirements.txt" ]; then
+    echo "ERROR: Missing requirements.txt"
+    exit 1
+elif [ ! -f "Cargo.toml" ]; then
+    echo "ERROR: Missing Cargo.toml"
+    exit 1
+fi
+
+# make sure these environment variables are set
+if [ -z ${GITHUB_TOKEN} ]; then
+    echo "ERROR: Missing environment variable \$GITHUB_TOKEN"
+    exit 1
+elif [ -z ${LOG_FILE} ]; then
+    echo "ERROR: Missing environment variable \$LOG_FILE"
+
+elif [ -z ${LOG_LEVEL} ]; then
+    echo "ERROR: Missing environment variable \$LOG_LEVEL"
+fi
+
+
 if [ $# != 1 ]; then
     echo "ERROR: Incorrect usage"
     echo "USAGE:"
@@ -16,43 +38,18 @@ elif [ $1 == "help" -o $1 == "--help" -o $1 == "-h" ]; then
     echo -e "\t./run <URL_FILE>"
     exit 1
 elif [ $1 == "install" ]; then
-    if [ ! -f "requirements.txt" ]; then
-        echo "ERROR: Missing requirements.txt"
-        exit 1
-    else
-        pip install --user -r requirements.txt
-        exit 0
-    fi
+    pip install --user -r requirements.txt
+    exit 0
 elif [ $1 == "build" ]; then
-    if [ ! -f "Cargo.toml" ]; then
-        echo "ERROR: Missing Cargo.toml"
-        exit 1
-    else
-        cargo build --release
-        exit 0
-    fi
+    cargo build --release
+    exit 0
 elif [ $1 == "test" ]; then
-    if [ ! -f "Cargo.toml" ]; then
-        echo "ERROR: Missing Cargo.toml"
-        exit 1
-    else
-        cargo build
-        exit 0
-    fi
+    cargo build
+    exit 0
 else
     if [ ! -f "target/release/ECE461_Team11" ]; then
-        if [ ! -f "Cargo.toml" ]; then
-            echo "ERROR: Missing Cargo.toml"
-            exit 1
-        fi
         cargo build --release
     fi
-
-    if [ -z ${GITHUB_TOKEN} ]; then
-        echo "ERROR: Missing environment variable \$GITHUB_TOKEN"
-        exit 1
-    fi
-
     ./target/release/ECE461_Team11 $1
     exit 0
 fi
